apiVersion: apps/v1
kind: Deployment # Create a deployment resource
metadata:
  name: nginx-deployment # Name of the Deployment
  labels:
    app: nginx # Labels to identify the application
spec:
  replicas: 2 # Number of pod replicas for high availability
  selector:
    matchLabels:
      app: nginx # Must match the labels in the template
  template:
    metadata:
      labels:
        app: nginx # Labels applied to the pods
    spec:
      containers:
      - name: nginx # Name of the container
        image: nginx:1.14.2 # Replace with the URL of your container image
        ports:
        - containerPort: 80 # Port the container listens on